=== kevin-bot/HTML-tareaCarnetXML/src/main/java/com/mycompany/tareacarnetmxl/tareaCarnetXMl.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT carnet (cabecera|cuerpo)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cabecera (imagencarnet|titulo)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT imagencarnet EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT titulo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cuerpo (foto|datosestudiante)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT foto (estudiante|fotoestudiante)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT estudiante (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fotoestudiante EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT datosestudiante (cede|codigo|nombre|apellido|ti|carrera)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cede (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT codigo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nombre (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT apellido (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ti (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT carrera (#PCDATA)>

=== kevin-bot/HTML-tareaCarnetXML/src/main/java/com/mycompany/tareacarnetmxl/tareaCarnetXMl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE carnet SYSTEM "tareaCarnetXMl.dtd">
<?xml-stylesheet href="tareaCarnetXMlStylesheet.css" type="text/css"?>
<carnet>
    
        <cabecera>
            <imagencarnet></imagencarnet>
            <titulo>Universidad del valle</titulo>
        </cabecera>
   
        <cuerpo>                  
            
            <foto>                
                <estudiante>Estudiante</estudiante>  
                <fotoestudiante></fotoestudiante>
            </foto>  
            
            <datosestudiante>
                <cede>Sede Caicedonia</cede>
                <codigo>201761914</codigo>
                <nombre>Kevin Santiago</nombre>
                <apellido>NARVAEZ VERA</apellido>
                <ti>T.I.  1003818315</ti>
                <carrera>Tecnologia en sistemas de 
                informacion</carrera>
            </datosestudiante>
        </cuerpo>
</carnet>
